name: Epic Building

on: [push,pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Change wrapper permissions cus github
      run: chmod +x ./gradlew
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build library jar
      run: ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: lib/build/libs/*.jar
